// PraxisOS · modul-baseret platform
//
// Hvert modul kan tilkøbes separat. Klinikker starter ofte med Practice Core,
// og tilføjer moduler efter behov (AI, AR, Physical AI, marketing, felt-service).

export type ModuleTier = "free" | "practice" | "ai" | "aesthetic" | "physical" | "enterprise";

export type Module = {
  id: string;
  name: string;
  shortName: string;
  tagline: string;
  description: string;
  category: "core" | "ai" | "clinical" | "compliance" | "growth" | "operations" | "platform";
  tier: ModuleTier;
  priceMonthly: number;           // kr/md
  pricePerSeat: number;            // kr/behandler/md
  pricingModel: "flat" | "per_seat" | "volume" | "free";
  iconColor: string;
  icon: string;                    // SVG path
  features: string[];
  dependsOn?: string[];           // moduler der kræves
  conflictsWith?: string[];       // moduler der ikke kan kombineres
  trialDays: number;
  popular?: boolean;
  enterprise?: boolean;
  agentRole?: string;             // hvis modulet drives af en specifik agent
  setupTimeMin: number;
  metricLabel: string;
  metricValue: string;
};

export const MODULES: Module[] = [
  // ---------- CORE ----------
  {
    id: "core-booking",
    name: "Booking & kalender",
    shortName: "Booking",
    tagline: "Online booking · uge-kalender · ressourcer",
    description: "Multi-tenant booking-system med online booking-side, kalender for behandlere, ressource-booking, venteliste, automatiske påmindelser og AI-foreslåede tider.",
    category: "core",
    tier: "free",
    priceMonthly: 0,
    pricePerSeat: 199,
    pricingModel: "per_seat",
    iconColor: "var(--color-accent)",
    icon: "M4 5h16v15H4zM4 9h16M8 3v4M16 3v4",
    features: [
      "Online booking-side under egen URL",
      "Kalender · dag/uge/måned · drag-to-create",
      "Real-time sync · Google Calendar integration",
      "Resource-booking · rum, udstyr, behandler-kombinationer",
      "Venteliste m. auto-promotion ved aflysninger",
      "SMS- og e-mail-påmindelser",
      "AI-foreslåede tider · no-show-buffer",
      "Embed-widget til kundens eget website",
    ],
    trialDays: 14,
    popular: true,
    setupTimeMin: 10,
    metricLabel: "Bookings · 30d",
    metricValue: "287",
  },
  {
    id: "core-clients",
    name: "Klient-DB & journal",
    shortName: "Klient · journal",
    tagline: "Multi-modal journal med samtykke og audit",
    description: "Komplet klient-database med GDPR Art. 9-samtykke, multi-modal journal (tekst, foto, AR-scan, måle-tidsserier), e-signering og fuld audit-log.",
    category: "core",
    tier: "practice",
    priceMonthly: 0,
    pricePerSeat: 150,
    pricingModel: "per_seat",
    iconColor: "var(--color-clay)",
    icon: "M4 20a6 6 0 0112 0M16 12a3 3 0 100-6M20 20a5 5 0 00-4-4.9M10 11a3.5 3.5 0 100-7 3.5 3.5 0 000 7z",
    features: [
      "Klient-DB · søgning · tags · segmenter",
      "GDPR Art. 9-samtykke + audit-log",
      "SOAP-skabeloner + frit format",
      "Multi-modal · foto · AR-scan · måle-tidsserier",
      "Forløb (treatment plans) med automatiske recall",
      "E-signering · eIDAS-niveau valgbart",
      "FHIR-eksport + ret-til-data-portabilitet",
    ],
    dependsOn: ["core-booking"],
    trialDays: 14,
    popular: true,
    setupTimeMin: 30,
    metricLabel: "Klienter",
    metricValue: "2.400+",
  },
  {
    id: "core-payments",
    name: "PraxisOS Pay",
    shortName: "Betaling",
    tagline: "MobilePay · Dankort · Klarna · Apple Pay",
    description: "Native payment-engine med MobilePay, Dankort, Apple Pay, Klarna og SEPA. PraxisRisk-scoring, PraxisTrust 2 step-up via MitID, daglig settlement til NemKonto.",
    category: "core",
    tier: "practice",
    priceMonthly: 0,
    pricePerSeat: 99,
    pricingModel: "per_seat",
    iconColor: "var(--color-signal)",
    icon: "M3 8h18M3 8V6a2 2 0 012-2h14a2 2 0 012 2v2M3 8v10a2 2 0 002 2h14a2 2 0 002-2V8M7 14h2M13 14h4",
    features: [
      "9 betalingsmetoder · MobilePay · Dankort · kort · wallets · BNPL",
      "PraxisRisk · ML-baseret risk-scoring",
      "PraxisTrust 2 · MitID step-up · 3DS-erstatning",
      "Auth-only mode · capture ved fremmøde",
      "Settlement · D+2 NemKonto",
      "Refunds · automatisk ved aflysning",
      "Forretningsmodel · 0.50% + 0.50 kr/tx",
    ],
    dependsOn: ["core-booking"],
    trialDays: 30,
    setupTimeMin: 60,
    metricLabel: "Brutto · 30d",
    metricValue: "48k kr",
  },

  // ---------- AI ----------
  {
    id: "ai-aria",
    name: "Aria · AI-receptionist",
    shortName: "Aria",
    tagline: "Autonom booking-agent · chat + voice + SMS",
    description: "Humaniseret AI-receptionist der besvarer 24/7 — booker, ombooker, aflyser og besvarer spørgsmål uden at lyde som en bot. Eskalerer til menneske ved klinisk usikkerhed.",
    category: "ai",
    tier: "ai",
    priceMonthly: 199,
    pricePerSeat: 0,
    pricingModel: "flat",
    iconColor: "#5d77a8",
    icon: "M5 4h14v11H8l-3 3zM9 9h.01M13 9h.01",
    features: [
      "Chat · voice · SMS · 24/7",
      "Auto-booking + ombooking + aflysning",
      "No-show prediktion · proaktive flows",
      "Eskalerer kun ved klinisk usikkerhed",
      "Patient-tilfredshed 4.9★",
    ],
    dependsOn: ["core-booking"],
    trialDays: 30,
    popular: true,
    agentRole: "Aria",
    setupTimeMin: 15,
    metricLabel: "Bookings auto · 30d",
    metricValue: "143",
  },
  {
    id: "ai-niels",
    name: "Niels · AI-scribe",
    shortName: "AI-scribe",
    tagline: "Ambient samtale → SOAP-journal automatisk",
    description: "Lytter til konsultationen og skriver et SOAP-udkast med ICD-10-koder mens du behandler. Du retter og signerer til sidst.",
    category: "ai",
    tier: "ai",
    priceMonthly: 0,
    pricePerSeat: 199,
    pricingModel: "per_seat",
    iconColor: "var(--color-ink)",
    icon: "M12 3a3 3 0 013 3v5a3 3 0 01-6 0V6a3 3 0 013-3zM5 11a7 7 0 0014 0M12 18v3",
    features: [
      "Whisper Large V3 transkription · EU-hostet",
      "Clinical BERT · medicinsk NER",
      "SOAP-strukturering · ICD-10-forslag",
      "47 min/dag sparet pr. behandler",
      "Behandler godkender altid før det gemmes",
    ],
    dependsOn: ["core-clients"],
    trialDays: 30,
    agentRole: "Niels",
    setupTimeMin: 5,
    metricLabel: "Noter · 30d",
    metricValue: "374",
  },
  {
    id: "ai-magnus",
    name: "Magnus · marketing-agent",
    shortName: "Magnus",
    tagline: "Recall · reviews · genbooking i din stemme",
    description: "Skriver beskeder der lyder som dig — ikke som en marketing-platform. Respekterer 100% opt-out og stopper helt ved klage.",
    category: "ai",
    tier: "ai",
    priceMonthly: 149,
    pricePerSeat: 0,
    pricingModel: "flat",
    iconColor: "var(--color-clay)",
    icon: "M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z",
    features: [
      "Auto-recall · 6 mdr inaktive",
      "Review-anmodning efter behandling",
      "Personaliserede nyhedsbreve",
      "100% opt-out-respekt · stopper ved klage",
      "Skriver i klinikkens stemme",
    ],
    dependsOn: ["core-clients"],
    trialDays: 14,
    agentRole: "Magnus",
    setupTimeMin: 30,
    metricLabel: "Genbookninger · 30d",
    metricValue: "38",
  },
  {
    id: "ai-liv",
    name: "Liv · patient-coach",
    shortName: "Liv",
    tagline: "Lytter mellem aftaler · holder dig i forløbet",
    description: "Omsorgsfuld AI-coach der stiller det rigtige spørgsmål på det rigtige tidspunkt. Giver aldrig medicinske råd — eskalerer altid til behandleren.",
    category: "ai",
    tier: "ai",
    priceMonthly: 99,
    pricePerSeat: 0,
    pricingModel: "flat",
    iconColor: "#c46a4a",
    icon: "M12 3a9 9 0 100 18 9 9 0 000-18zM12 12c4 0 7 2.5 7 5.5M5 17.5c0-3 3-5.5 7-5.5",
    features: [
      "Check-ins mellem aftaler",
      "Forløbs-fastholdelse · 94% rate",
      "Adherence-tracking",
      "Eskalerer altid til behandler ved klinisk spørgsmål",
    ],
    dependsOn: ["core-clients"],
    trialDays: 30,
    agentRole: "Liv",
    setupTimeMin: 10,
    metricLabel: "Check-in respons",
    metricValue: "78%",
  },

  // ---------- CLINICAL ----------
  {
    id: "clinical-ar-journal",
    name: "AR/CV-journal",
    shortName: "AR-journal",
    tagline: "Foto-progression · TruSkin-age · time-series",
    description: "Før/efter-slider, AR-baseret hud-/sår-analyse, kvantitative parametre over tid, automatiske AI-genererede noter.",
    category: "clinical",
    tier: "aesthetic",
    priceMonthly: 0,
    pricePerSeat: 299,
    pricingModel: "per_seat",
    iconColor: "var(--color-accent)",
    icon: "M3 7v10a2 2 0 002 2h14a2 2 0 002-2V7M21 7H3M21 7l-3-4H6L3 7M9 11l3 3 3-3",
    features: [
      "Foto-capture m. positionsguide",
      "AR hud-analyse · 14 concerns",
      "TruSkin Age scoring",
      "Time-series slider · før/efter",
      "Æstetisk simulator · 27 procedurer",
      "Sår-/læsions-måling",
    ],
    dependsOn: ["core-clients"],
    trialDays: 30,
    setupTimeMin: 30,
    metricLabel: "Scans · 30d",
    metricValue: "84",
  },
  {
    id: "clinical-foot-scan",
    name: "Physical AI · Fod-scan",
    shortName: "Fod-scan",
    tagline: "Sub-mm 3D-topologi · plantar pressure · biomarkers",
    description: "3D-mesh roterbar · plantar pressure heatmap · hallux valgus + navicular drop · termisk + vaskulær screening · 3-agent swarm med Cosmos 3.",
    category: "clinical",
    tier: "physical",
    priceMonthly: 1499,
    pricePerSeat: 0,
    pricingModel: "flat",
    iconColor: "var(--color-clay)",
    icon: "M9 2c-2 0-3 2-3 5 0 2 1 3 1 5s-1 4-1 6c0 2 1 4 3 4s3-2 3-4-1-2-1-4c0-3 1-5 1-7 0-3-1-5-3-5z",
    features: [
      "3 vinkler · top · side · bund",
      "3D-mesh roterbar · 312k punkter",
      "Plantar pressure · 4.096 sensorer",
      "Hallux valgus + navicular drop måling",
      "Termisk + vaskulær biomarkers",
      "3-agent swarm · sub-mm præcision",
      "+ Hardware-bundle: 12.500 kr/enkeltsetup",
    ],
    dependsOn: ["core-clients"],
    trialDays: 14,
    enterprise: true,
    setupTimeMin: 240,
    metricLabel: "Scans · 30d",
    metricValue: "52",
  },

  // ---------- COMPLIANCE & DK ----------
  {
    id: "compliance-mitid",
    name: "MitID · Erhverv & privat",
    shortName: "MitID",
    tagline: "Officiel eID · Signaturgruppen-broker",
    description: "Patient + kliniker login via MitID. NSIS Substantial niveau · CPR Match for privat SaaS · stort produktets compliance-fundament.",
    category: "compliance",
    tier: "practice",
    priceMonthly: 99,
    pricePerSeat: 0,
    pricingModel: "flat",
    iconColor: "#0061af",
    icon: "M12 2l8 4v6c0 5-3.5 8-8 10-4.5-2-8-5-8-10V6zM9 12l2 2 4-4",
    features: [
      "MitID privat (patienter)",
      "MitID Erhverv (klinikere)",
      "CPR Match for privat SaaS",
      "NSIS Substantial default · High til journal-write",
      "Signaturgruppen-broker · EU-resident",
    ],
    trialDays: 0,
    popular: true,
    setupTimeMin: 120,
    metricLabel: "Logins · 30d",
    metricValue: "1.247",
  },
  {
    id: "compliance-nemsms",
    name: "NemSMS",
    shortName: "NemSMS",
    tagline: "Officiel sundheds-SMS via Sundhedsdatanettet",
    description: "Send påmindelser, recept-notifikationer, behandlings-resultater via officiel NemSMS. Gratis for borgeren · 0,50 kr/SMS for klinik.",
    category: "compliance",
    tier: "practice",
    priceMonthly: 0,
    pricePerSeat: 0,
    pricingModel: "volume",
    iconColor: "#5A78FF",
    icon: "M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z",
    features: [
      "Booking-bekræftelser",
      "24t / 1t påmindelser",
      "Aflysninger · receptbesked · resultater",
      "KOMBIT-registreret sender-ID",
      "5 års retention iht. sundhedslov",
      "0,50 kr pr. SMS",
    ],
    dependsOn: ["core-booking", "compliance-mitid"],
    trialDays: 7,
    setupTimeMin: 30,
    metricLabel: "Sendt · 30d",
    metricValue: "287",
  },
  {
    id: "compliance-subsidies",
    name: "Tilskud & indberetning",
    shortName: "Tilskud",
    tagline: "Sigrid · 9 ordninger · auto-indberetning",
    description: "Automatisk beregning af bedste tilskud + indberetning til Sygesikringen «danmark», kommuner, MedCom og privat forsikring. EDI, MedCom XML, KOMBIT API.",
    category: "compliance",
    tier: "ai",
    priceMonthly: 249,
    pricePerSeat: 0,
    pricingModel: "flat",
    iconColor: "var(--color-signal)",
    icon: "M12 1v22M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6",
    features: [
      "9 danske tilskudsordninger",
      "Live beregning af bedste valg",
      "Auto-indberetning · EDI · MedCom · KOMBIT",
      "Sigrid · agent-styret · ingen manuel arbejde",
      "Ack-handling med retry + DLQ",
      "Settlement-match til NemKonto",
    ],
    dependsOn: ["core-booking", "core-clients"],
    trialDays: 30,
    popular: true,
    agentRole: "Sigrid",
    setupTimeMin: 60,
    metricLabel: "Refunderet · 30d",
    metricValue: "142k kr",
  },
  {
    id: "compliance-medcom",
    name: "MedCom",
    shortName: "MedCom",
    tagline: "Henvisninger · epikriser · sygesikringsafregning",
    description: "Komplet MedCom-integration · modtag og send henvisninger, epikriser, lab-svar og elektronisk afregning til Region/Sygesikring.",
    category: "compliance",
    tier: "enterprise",
    priceMonthly: 499,
    pricePerSeat: 0,
    pricingModel: "flat",
    iconColor: "var(--color-accent)",
    icon: "M4 4h16v16H4zM4 9h16M9 4v16",
    features: [
      "MedCom XML · alle standard-typer",
      "VANS · Sundhedsdatanettet routing",
      "DK-02 semantisk ack",
      "EAN-baseret addressing",
      "Indbakke + sendte med fuld historik",
    ],
    dependsOn: ["compliance-mitid", "compliance-subsidies"],
    trialDays: 0,
    enterprise: true,
    setupTimeMin: 480,
    metricLabel: "Beskeder · 30d",
    metricValue: "84",
  },
  {
    id: "compliance-sundhed-dk",
    name: "Sundhed.dk + FMK",
    shortName: "Sundhed.dk",
    tagline: "National federation · FMK-opslag · Min Log",
    description: "SSO mod sundhed.dk · adgang til Fælles Medicinkort · automatisk synkronisering med patientens Min Log · kræver trustaftale.",
    category: "compliance",
    tier: "enterprise",
    priceMonthly: 799,
    pricePerSeat: 0,
    pricingModel: "flat",
    iconColor: "var(--color-signal)",
    icon: "M22 11.08V12a10 10 0 11-5.93-9.14M22 4l-10 10-3-3",
    features: [
      "SSO mod sundhed.dk",
      "FMK-opslag · medicin + recepter",
      "Min Log · synlig for patient",
      "Trustaftale med Sundhedsdatastyrelsen",
      "Krav: MitID Erhverv + Trustaftale",
    ],
    dependsOn: ["compliance-mitid", "compliance-medcom"],
    trialDays: 0,
    enterprise: true,
    setupTimeMin: 60480, // 6 uger
    metricLabel: "Trustaftale",
    metricValue: "i gang",
  },

  // ---------- GROWTH ----------
  {
    id: "growth-vouchers",
    name: "Klippekort & gavekort",
    shortName: "Vouchers",
    tagline: "Forudbetalte pakker · brand-tilpassede gavekort",
    description: "Sælg klippekort (forudbetalt bundt af sessioner med rabat) og gavekort (DKK-baseret med 3 års udløb iht. dansk lov).",
    category: "growth",
    tier: "practice",
    priceMonthly: 99,
    pricePerSeat: 0,
    pricingModel: "flat",
    iconColor: "var(--color-clay)",
    icon: "M21 16V8a2 2 0 00-1-1.7l-7-4a2 2 0 00-2 0l-7 4A2 2 0 003 8v8a2 2 0 001 1.7l7 4a2 2 0 002 0l7-4A2 2 0 0021 16zM3.3 7l8.7 5 8.7-5M12 22V12",
    features: [
      "Klippekort med rabat",
      "Gavekort med hilsen + udløb",
      "3-i-1 split-payment ved booking",
      "Auto-mail til modtager med kode",
      "Saldo-tracking pr. voucher",
    ],
    dependsOn: ["core-booking", "core-payments"],
    trialDays: 14,
    setupTimeMin: 30,
    metricLabel: "Solgt · 30d",
    metricValue: "23",
  },

  // ---------- OPERATIONS ----------
  {
    id: "ops-field",
    name: "Felt-service",
    shortName: "Felt",
    tagline: "Bjørn · offline-first mobil · ML-rute-optimering",
    description: "Hjemmebesøg-modul med ML-baseret rute-optimering, offline-first mobil-app og tilgængeligheds-tjek (parkering, elevator, etage).",
    category: "operations",
    tier: "practice",
    priceMonthly: 149,
    pricePerSeat: 0,
    pricingModel: "flat",
    iconColor: "#8a6a3d",
    icon: "M3 7l9-4 9 4-9 4-9-4zM3 7v6l9 4 9-4V7",
    features: [
      "ML-rute-optimering · 22 min/dag sparet",
      "Offline-first mobil-app",
      "Tilgængeligheds-tjek pr. besøg",
      "Bjørn · agent-koordineret",
    ],
    dependsOn: ["core-booking"],
    trialDays: 14,
    agentRole: "Bjørn",
    setupTimeMin: 60,
    metricLabel: "Besøg · 30d",
    metricValue: "34",
  },
  {
    id: "ops-finance",
    name: "Finans & cash-flow",
    shortName: "Finans",
    tagline: "Vega · cash-flow prognose · auto-rykkere",
    description: "Daglig settlement + cash-flow-prognose · Vega sender venlige rykkere ved ubetalt > 14 dage · auto-bogføring i Dinero/e-conomic/Billy.",
    category: "operations",
    tier: "ai",
    priceMonthly: 149,
    pricePerSeat: 0,
    pricingModel: "flat",
    iconColor: "var(--color-accent)",
    icon: "M3 3v18h18M7 17l4-4 4 4 6-6",
    features: [
      "30-dages cash-flow prognose",
      "Auto-rykkere · venlige · ikke pushy",
      "Auto-bogføring i e-conomic/Dinero/Billy",
      "Settlement-match",
      "Vega · agent-styret",
    ],
    dependsOn: ["core-payments"],
    trialDays: 14,
    agentRole: "Vega",
    setupTimeMin: 30,
    metricLabel: "Cash-flow · 30d",
    metricValue: "+12%",
  },
  {
    id: "ops-security",
    name: "Frej · sikkerhed",
    shortName: "Sikkerhed",
    tagline: "Audit-log · anomaly detection · GDPR-overvågning",
    description: "Compliance-agent der overvåger uberettiget journal-opslag i realtid · audit-log med hash-chain · patient-synlig på Min Side.",
    category: "compliance",
    tier: "practice",
    priceMonthly: 99,
    pricePerSeat: 0,
    pricingModel: "flat",
    iconColor: "var(--color-amber)",
    icon: "M12 2l8 4v6c0 5-3.5 8-8 10-4.5-2-8-5-8-10V6z",
    features: [
      "Real-time anomaly detection",
      "GDPR Art. 30 audit-log · hash-chained",
      "Patient-synlig · «hvem har set min journal»",
      "TOR/VPN blokade · rate-limiting",
      "Datatilsynet-eksport",
      "Frej · agent-styret",
    ],
    dependsOn: ["compliance-mitid"],
    trialDays: 0,
    agentRole: "Frej",
    setupTimeMin: 10,
    metricLabel: "Anomalies · 30d",
    metricValue: "2 blokeret",
  },

  // ---------- PLATFORM ----------
  {
    id: "platform-api",
    name: "Universal API + MCP",
    shortName: "API + MCP",
    tagline: "REST API · webhooks · MCP for Claude Code",
    description: "Komplet REST API til ekstern integration · webhooks · MCP-server så Claude Code og Cursor kan styre PraxisOS direkte.",
    category: "platform",
    tier: "ai",
    priceMonthly: 299,
    pricePerSeat: 0,
    pricingModel: "flat",
    iconColor: "var(--color-faint)",
    icon: "M4 16l-3-3 3-3M20 8l3 3-3 3M14 4l-4 16",
    features: [
      "REST API · 25+ endpoints",
      "Webhooks · 12 event-typer",
      "MCP-server · 19 tools til Claude Code",
      "API-keys med scopes",
      "Rate-limit 600/min default",
      "OpenAPI 3.1 spec",
    ],
    trialDays: 30,
    setupTimeMin: 15,
    metricLabel: "API-calls · 30d",
    metricValue: "47k",
  },
  {
    id: "platform-atlas",
    name: "Atlas · platform-engineer",
    shortName: "Atlas",
    tagline: "Self-reflecting code-gen · auto-optimering",
    description: "Atlas optimerer platformen mens du sover · genskriver pipelines · genererer tests · alt i skygge-mode indtil din godkendelse.",
    category: "platform",
    tier: "enterprise",
    priceMonthly: 999,
    pricePerSeat: 0,
    pricingModel: "flat",
    iconColor: "var(--color-muted)",
    icon: "M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5",
    features: [
      "Self-reflecting code-gen",
      "Auto-test-generering",
      "Performance-optimering · CI-grøn først",
      "Rollback-protection",
      "Atlas · agent-styret",
    ],
    trialDays: 0,
    enterprise: true,
    agentRole: "Atlas",
    setupTimeMin: 60,
    metricLabel: "Optimering · 7d",
    metricValue: "−14% mem",
  },
];

export const CATEGORIES = [
  { id: "core",       label: "Kerne",            desc: "Booking · klient · betaling",          color: "var(--color-ink)" },
  { id: "ai",         label: "AI-agenter",       desc: "Aria · Niels · Magnus · Liv · Sigrid · Vega · Frej · Bjørn · Atlas", color: "var(--color-clay)" },
  { id: "clinical",   label: "Klinisk",          desc: "AR/CV-journal · Physical AI",          color: "var(--color-signal)" },
  { id: "compliance", label: "DK · compliance",  desc: "MitID · NemSMS · MedCom · Sundhed.dk", color: "#0061af" },
  { id: "growth",     label: "Vækst",            desc: "Vouchers · marketing · recall",         color: "var(--color-accent)" },
  { id: "operations", label: "Drift",            desc: "Felt-service · finans · sikkerhed",     color: "var(--color-amber)" },
  { id: "platform",   label: "Platform",         desc: "API · MCP · self-optimization",         color: "var(--color-faint)" },
] as const;

// Mock active modules per tenant
export const TENANT_ACTIVE_MODULES: Record<string, string[]> = {
  bypilar: [
    "core-booking",
    "core-clients",
    "core-payments",
    "ai-aria",
    "ai-niels",
    "clinical-foot-scan",
    "clinical-ar-journal",
    "compliance-mitid",
    "compliance-nemsms",
    "compliance-subsidies",
    "growth-vouchers",
    "ops-finance",
    "ops-security",
    "platform-api",
  ],
  nordlys: ["core-booking", "core-clients", "core-payments", "ai-aria", "ai-niels", "ai-magnus", "compliance-mitid", "clinical-ar-journal", "ops-security", "platform-api"],
};

export function getModule(id: string): Module | undefined {
  return MODULES.find((m) => m.id === id);
}

export function isModuleActive(tenant: string, moduleId: string): boolean {
  return TENANT_ACTIVE_MODULES[tenant]?.includes(moduleId) ?? false;
}

export function calculateTotalCost(tenant: string, seats: number): { perMonth: number; perSeat: number; flat: number; total: number; modules: { id: string; name: string; cost: number }[] } {
  const active = TENANT_ACTIVE_MODULES[tenant] ?? [];
  const breakdown = active.map((id) => {
    const m = getModule(id)!;
    const cost = m.pricingModel === "flat" ? m.priceMonthly : m.pricingModel === "per_seat" ? m.pricePerSeat * seats : 0;
    return { id: m.id, name: m.name, cost };
  });
  const flat = active.reduce((s, id) => s + (getModule(id)?.priceMonthly ?? 0), 0);
  const perSeat = active.reduce((s, id) => {
    const m = getModule(id);
    return s + (m?.pricingModel === "per_seat" ? m.pricePerSeat * seats : 0);
  }, 0);
  return { perMonth: flat + perSeat, perSeat, flat, total: flat + perSeat, modules: breakdown };
}
